
services:

  api:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api_container
    stdin_open: true
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    