FROM python:3.11-slim 
WORKDIR /app
COPY ./app/requirements.txt .
RUN pip install --upgrade pip
RUN pip install debugpy
RUN pip install flask
RUN pip install flask-cors
RUN pip install -r requirements.txt
RUN pip install -qU langchain-community langchain-experimental langgraph langchain-openai chromadb matplotlib
CMD ["python", "run.py"]